---

# Yum
- name: Install base tools (Yum)
  yum:
    name:
      - curl
      - gcc
      - gcc-c++
      - make
      - rsync
      - wget
    state: present
  when: ansible_pkg_mgr == 'yum'

# Aptitude
- name: Install base tools (Aptitude)
  apt:
    name:
      - build-essential
      - curl
      - rsync
      - wget
    state: present
  when: ansible_pkg_mgr == 'apt'

# Homebrew
- name: Install base tools (Homebrew)
  homebrew:
    name:
      - curl
      - rsync
      - wget
    state: present
  become: true
  become_user: "{{ base_tools_homebrew_user }}"
  when: ansible_pkg_mgr == 'homebrew'

# Other package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Aptitude, Homebrew or Yum are supported)"
  when: ansible_pkg_mgr != 'yum' and ansible_pkg_mgr != 'apt' and ansible_pkg_mgr != 'homebrew'
