---

# Yum
- name: Install base tools (Yum)
  yum: pkg={{ item }} state=present
  with_items:
    - curl
    - gcc
    - gcc-c++
    - make
    - rsync
    - wget
  when: ansible_pkg_mgr == 'yum'

# Aptitude
- name: Install base tools (Aptitude)
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - curl
    - rsync
    - wget
  when: ansible_pkg_mgr == 'apt'

# Homebrew
- name: Install base tools (Homebrew)
  homebrew: name={{ item }} state=present
  become: true
  become_user: "{{ base_tools_homebrew_user }}"
  with_items:
    - curl
    - rsync
    - wget
  when: ansible_pkg_mgr == 'homebrew'

# Other package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Aptitude, Homebrew or Yum are supported)"
  when: ansible_pkg_mgr != 'yum' and ansible_pkg_mgr != 'apt' and ansible_pkg_mgr != 'homebrew'
